name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  binary_tree:
    name: Build "Binary tree" homework
    runs-on: ${{matrix.os}}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        build_type: [Debug, Release]

    defaults:
      run:
        working-directory: ${{github.workspace}}/binary-tree
        shell: bash

    steps:
    - uses: actions/checkout@v2

    - name: Configure CMake
      run: cmake -B build -DCMAKE_BUILD_TYPE=${{matrix.build_type}}

    - name: Build project
      run: cmake --build build --config ${{matrix.build_type}}

    - name: Run tests
      run: |
        cd build
        ctest -C ${{matrix.build_type}}

  stable_selection_sort:
    name: Build "Stable selection sort" homework
    runs-on: ${{matrix.os}}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        build_type: [Debug, Release]

    defaults:
      run:
        working-directory: ${{github.workspace}}/binary-tree
        shell: bash

    steps:
    - uses: actions/checkout@v2

    - name: Configure CMake
      run: cmake -B build -DCMAKE_BUILD_TYPE=${{matrix.build_type}}

    - name: Build project
      run: cmake --build build --config ${{matrix.build_type}}

    - name: Run tests
      run: |
        cd build
        ctest -C ${{matrix.build_type}}


